[workspace]
members = [
  "crates/sc-sha-go",
  "crates/sc-sha",
  "crates/sc-compose",
  "crates/sc-composer",
  "crates/atmcore",
  "crates/filesystem-support",
  "crates/sc-sha-python",
  "crates/uniffi",
  "crates/thiserror",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.94.1"
authors = ["sc-compose"]
license = "MIT"
